### PR TITLE
Use python3 for virtualenv

### PR DESCRIPTION
**Pull request by RealDeuce**
Trying to use install-octopi.sh installed a python2 virtualenv.
Replace all instances of "python2" with "python3" and all instances
of "python-dev" with "python3-dev".

### CODE REVIEW

**Comment by RealDeuce** [comment]
Trying to follow install instructions installed Python 2.7 :(

**Comment by Doridian** [comment]
@RealDeuce Some of the files you changed now call the universal `python` and not fixed `python2`, so they should work on python3 by default.
I suggest just removing these changes from your PR entirely. Maybe go with `python` in general unless files specifically depend on py2 to avoid more errors with klipper making some things 3 compatible?

**Comment by RealDeuce** [comment]
So actually running the install-octopi.sh script installed the python-is-python2 and python-dev-is-python2 packages on my Ubuntu system and I had to clean up that mess, but OK.

As for "now" I'm not sure what that is, is python3 the wrong branch to follow?

**Comment by Doridian** [comment]
@RealDeuce upstream (KevinOConnor/klipper, which this one is forked from) did some updates where they altered python2 to python

Example commit: https://github.com/KevinOConnor/klipper/commit/4d5c619b8eb7aa530a87304cc26734f42e2d2b0d

That is what I meant by "now".

**Comment by RealDeuce** [comment]
Will open a separate PR for just install scripts.

**Pull request closed without merging**
